language: cpp
dist: bionic
sudo: required

env:
  # Turn off all RPC layers by default. They will be enabled one-by-one in the
  # build matrix
  global:
    - HCL_ENABLE_RPCLIB=OFF
    - HCL_ENABLE_THALLIUM_TCP=OFF
    - HCL_ENABLE_THALLIUM_ROCE=OFF

# Install APT dependencies
addons:
  apt:
    packages:
      - libboost-dev
      - libmpich-dev

thallium_deps: &thallium_deps
  - ./ci/install_libfabric.sh
  - ./ci/install_mercury.sh
  - ./ci/install_argobots.sh
  - ./ci/install_margo.sh
  - ./ci/install_thallium.sh

matrix:
  include:
  - env: HCL_ENABLE_RPCLIB=ON
    before_install: ./ci/install_rpclib.sh
  - env: HCL_ENABLE_THALLIUM_TCP=ON
    before_install: *thallium_deps
  - env: HCL_ENABLE_THALLIUM_ROCE=ON
    before_install: *thallium_deps

script: ./ci/install_hcl.sh
